Algoritmo "L4E9"
//Fazer um algoritmo que pergunte a idade de uma pessoa, e ao final, informe na tela se a pessoa ? menor de
//idade, se ? maior de idade, ou se ? maior de 65 anos.
Var
idade: inteiro


Inicio
Escreva("Digite a sua idade: ")
leia(idade)

se idade < 18 entao
   escreva("Voc? ? menor de idade")
senao
   se idade <= 65 entao
      escreva("Voc? ? maior de idade")
   senao:
         escreva("Voc? ? maior de 65 anos")
fimse
fimse
Fimalgoritmo


Fimalgoritmo