Algoritmo "L5E3"
//Desenvolver um programa que apresente os quadrados dos números de 15 a 200
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 15
enquanto ( contador <= 200 ) faca
         escreval ("O quadrado do número ", contador, " é ", contador * contador)
         contador <- contador + 1
fimenquanto

Fimalgoritmo