Algoritmo "L5E4"
//Desenvolver um programa que apresente a soma dos 100 primeiros números
Var
// Seção de Declarações das variáveis 
contador, acumulador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 1
acumulador <- 0

enquanto ( contador <= 100 ) faca
         acumulador <- acumulador + contador
         contador <- contador + 1
fimenquanto

escreval ( acumulador )

Fimalgoritmo