Algoritmo "L4.3E12"
//Matriz diagonal de 10
Var
// Seção de Declarações das variáveis 
cont1, cont2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para cont1 de 1 ate 10 passo 1 faca
     para cont2 de 1 ate 10 passo 1 faca
          se ( cont1 >= cont2 ) entao
             escreva ( " x - x " )
          senao
               escreva ( cont1," -",cont2, " " )
          fimse
     fimpara
     escreval
fimpara
Fimalgoritmo
