Algoritmo "L4.3E11"
//Matriz de 10
Var
// Seção de Declarações das variáveis 
cont1, cont2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para cont1 de 1 ate 10 passo 1 faca
     para cont2 de 1 ate 10 passo 1 faca
          se ( cont1 < 10 ) entao
             escreva ( " ",cont1," -",cont2, " " )
          senao
               escreva ( cont1," -",cont2, " " )
          fimse
     fimpara
     escreval
fimpara
Fimalgoritmo