Algoritmo "L4E1"
//1.	Fazer um algoritmo que peça um número, e ao final, informe se o número
//digitado está acima de 1000 ou abaixo de 1000.
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Me diga um número: ")
leia (num)

se (num >= 1000)entao
    escreval ("O número", num, " está acima de 1000.")
senao:
    escreval ("O número", num, " está abaixo de 1000.")
fimse
Fimalgoritmo